dist: trusty
sudo: required

language: python
python:
- 2.7

env:
  global:
    - secure: aZWcHZWV8lN2SNU2fcUsG8+fVQLOxwDUFYDvuftZALebRG2AHINTkbS31sKbeSwS19ZYpjcuVOKC9HxNAlnMxsdO1NvvFEbSJJD/yqq0V4EfTRqptZYsFCUou0eXIUWEnoFHD1nY3NhuPQjDoad995xU92z0BzwduxUAj28liu4=

before_install:
- cat /etc/apt/sources.list.d/*
- rm --recursive --force /home/travis/.nvm
- sudo rm --force /usr/local/bin/docker-compose
- sudo rm --recursive --force /var/lib/apt/lists/*
- sudo apt-get remove --assume-yes --force-yes python-zope.interface postgresql-*
- sudo apt-get install --assume-yes --force-yes aptitude
- curl --silent --location https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo aptitude install --assume-yes apache2 libapache2-mod-wsgi libapache2-mod-fcgid tomcat7 nodejs cgi-mapserver gettext
- sudo chmod  o+rx /var/log/apache2/
- sudo chmod  o+r /var/log/apache2/*.log
- sudo apt-get install --option Dpkg::Options::="--force-confold" --force-yes --assume-yes docker-ce
- sudo pip install pyignore git+https://github.com/docker/docker-py.git@1.10.6#egg=docker docker-compose==1.9.0 requests==2.11.1

- sudo service postgresql stop

# database for the GeoMapFish application
- docker build --tag=geomapfish-db docker/test-db
- docker run --publish=5432:5432 --detach geomapfish-db

- docker build --tag=external-db docker/test-external-db
- docker run --publish=5433:5432 --detach external-db

- |
  if [ "${TX_PASS}" != "" ]
  then
  echo "[https://www.transifex.com]" >> ~/.transifexrc
  echo "hostname = https://www.transifex.com" >> ~/.transifexrc
  echo "username = stephane.brunner@camptocamp.com" >> ~/.transifexrc
  echo "password = ${TX_PASS}" >> ~/.transifexrc
  echo "token =" >> ~/.transifexrc
  fi
- export TRAVIS_FOLDER=`pwd`
- mkdir --parents /tmp/travis/testgeomapfish
- |
    if travis/git-modif docker/build
    then
        docker build --tag=camptocamp/geomapfish_build_dev:2.2 docker/build
    else
        docker pull camptocamp/geomapfish_build_dev:2.2
    fi
- |
    [[ `./docker-run id` =~ uid=[0-9]+\(travis\)\ gid=[0-9]+\(geomapfish\)\ groups=[0-9]+\(geomapfish\) ]]

install:
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git fetch origin ${TRAVIS_BRANCH}:${TRAVIS_BRANCH}; fi
- ./docker-run make -f travis.mk build

- pip install sqlalchemy psycopg2
- python travis/waitdb postgres://www-data:www-data@localhost/geomapfish_test

script:
- uname --all
- node --version
- npm --version
- python setup.py --version
- docker version

- ./docker-run make -f travis.mk doc

after_success:
- ./docker-run coveralls
- openssl aes-256-cbc -K $encrypted_ae821512cabf_key -iv $encrypted_ae821512cabf_iv -in deploy_key.enc -out ~/.ssh/id_rsa -d | true
- chmod 600 ~/.ssh/id_rsa
- git config --global user.email travis@camptocamp.com
- git config --global user.name Travis
- git remote set-url origin git@github.com:camptocamp/c2cgeoportal.git
- GIT_REV=`git log | head --lines=1 | awk '{{print $2}}'`
- |
  if [ "${TRAVIS_REPO_SLUG}-${TRAVIS_PULL_REQUEST}" == camptocamp/c2cgeoportal-false ]
  then
    travis/doc.sh
  fi

before_deploy:
- git checkout ${GIT_REV}
- if [[ ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\..+$ ]] ; then
  sed --expression 's/REQUIREMENTS [\?]= c2cgeoportal/REQUIREMENTS ?= c2cgeoportal=='"${TRAVIS_TAG}"'/g' --in-place c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl;
  sed --expression 's/version="[0-9]\+\.[0-9]\+",/version="'"${TRAVIS_TAG}"'",/g' --in-place setup.py;
  git diff;
  fi

deploy:
- provider: script
  script: travis/doc.sh
  skip_cleanup: true
  on:
    repo: camptocamp/c2cgeoportal
    branch: doc22
    condition: '"${TRAVIS_PULL_REQUEST}" = false'

notifications:
  email:
    on_failure: change
